### PR TITLE
Initial setup instructions

### PR DESCRIPTION
**Pull request by akampjes**
Just the start, needs more solid insturctions and testing default machines.

Hopefully with some install and setup instructions it will be easier for people to get the project setup to play with.

### CODE REVIEW

**Comment by akampjes** [comment]
Ja I saw. I'll rebase mine ontop and sync up the changes.

**Comment by ladynerd** [comment]
Grand :)

**Comment by akampjes** [comment]
@ladynerd Could I get you to make a commit of your pip packages too with `pip freeze > config/requirements.txt` since ours didn't quite match up and from @geckonz install instructions it looks like at least one was missing (which I added back in).

**Comment by ladynerd** [comment]
sure

**Comment by ladynerd** [comment]
done :)

**Comment by akampjes** [comment]
Sweet, requirements file matches mine too now.

Fixed up my patch. The renamings are from what I understand to be the most common conventions for naming. I can rename them if you want though.

**Pull request merged**
